import { Noto_Sans } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: "MT",
  description: "Generated by Next.js",
};

const font = Noto_Sans({ subsets: ["latin", "cyrillic"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
